### ISSUE TITLE
bug-0001-TypeError: document.querySelector(...) is null

### ISSUE THREAD

**Issue by malekinho8** [cmprmsd/Overleaf-Image-Helper#6]
Whenever I try to `console.log(document.querySelector('.ace_editor'))`, it returns `null` when using the new Overleaf Editor. The problem can be circumvented by selecting `Source (Legacy)` just above the editor window, but this is not ideal. It appears the old Ace Editor has been replaced by CodeMirror6:

https://www.overleaf.com/learn/how-to/How_can_I_define_custom_Vim_macros_in_a_vimrc_file_on_Overleaf%3F

**Comment by cmprmsd** [comment]
Yup yup. I opened several issues at Overleaf in order to get this feature implemented upstream in the project. However nothing happened. "they consider implementing this feature". ^^

Once the Overleaf team updates the open source version that we can self host, I'll have a look at it and will try to come up with a patch. 

Navigating around the DOM is a pain :D 

How do you like the new editor?

**Comment by malekinho8** [comment]
Yeah, sounds good. I'm not sure why they don't have this feature implemented natively, because it has saved me so much time. To be honest, I haven't really had a chance to use the new editor too much... Do you know why they changed it or why the new editor is better?

**Comment by cmprmsd** [comment]
Closing in favor of https://github.com/cmprmsd/Overleaf-Image-Helper/issues/2 to track this issue as soon as the community edition will be released with the new editor.
